# Generated by Django 5.0.8 on 2026-02-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g. '3 Months'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of key features'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text="e.g. 'Full Stack Development'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solutions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Full project description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Main project image', null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.TextField(help_text='Short summary for cards'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.JSONField(default=list, help_text="List of tags (e.g. ['Featured', 'Web'])"),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(default=list, help_text="List of technologies used (e.g. ['React', 'Django'])"),
        ),
    ]
