# Generated by Django 5.0.8 on 2026-02-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('gradient', models.CharField(help_text='Tailwind gradient classes', max_length=100)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('color', models.CharField(help_text='Hex color code', max_length=20)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Databases', 'Databases'), ('Cloud Solutions', 'Cloud Solutions'), ('DevOps', 'DevOps'), ('Mobile', 'Mobile'), ('Other', 'Other')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Technologies',
            },
        ),
    ]
