# Generated by Django 5.0.8 on 2025-12-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Company Name', max_length=255)),
                ('contact_email', models.EmailField(default='contact@example.com', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/')),
            ],
            options={
                'verbose_name': 'Site Configuration',
                'verbose_name_plural': 'Site Configuration',
            },
        ),
    ]
