# Generated by Django 5.0.8 on 2026-02-04 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('primary', models.CharField(help_text='Main brand color (hex)', max_length=7)),
                ('primary_light', models.CharField(blank=True, max_length=7)),
                ('primary_dark', models.CharField(blank=True, max_length=7)),
                ('secondary', models.CharField(help_text='Secondary brand color (hex)', max_length=7)),
                ('secondary_light', models.CharField(blank=True, max_length=7)),
                ('secondary_dark', models.CharField(blank=True, max_length=7)),
                ('accent', models.CharField(help_text='Accent color (hex)', max_length=7)),
                ('accent_light', models.CharField(blank=True, max_length=7)),
                ('accent_dark', models.CharField(blank=True, max_length=7)),
                ('success', models.CharField(default='#10b981', max_length=7)),
                ('warning', models.CharField(default='#f59e0b', max_length=7)),
                ('error', models.CharField(default='#ef4444', max_length=7)),
                ('info', models.CharField(default='#3b82f6', max_length=7)),
                ('background', models.CharField(default='#ffffff', max_length=7)),
                ('surface', models.CharField(default='#f9fafb', max_length=7)),
                ('text_primary', models.CharField(default='#111827', max_length=7)),
                ('text_secondary', models.CharField(default='#6b7280', max_length=7)),
                ('border', models.CharField(default='#e5e7eb', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Color Palette',
                'verbose_name_plural': 'Color Palettes',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('button', 'Button'), ('link', 'Link'), ('card', 'Card'), ('navbar', 'Navigation Bar'), ('footer', 'Footer'), ('form', 'Form'), ('badge', 'Badge'), ('alert', 'Alert'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('color_value', models.CharField(help_text='Hex color code', max_length=7)),
                ('hover_color', models.CharField(blank=True, help_text='Hover state color', max_length=7)),
                ('active_color', models.CharField(blank=True, help_text='Active state color', max_length=7)),
                ('disabled_color', models.CharField(blank=True, help_text='Disabled state color', max_length=7)),
                ('css_variable', models.CharField(help_text='e.g., --btn-primary', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Custom Color',
                'verbose_name_plural': 'Custom Colors',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GradientPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('gradient_type', models.CharField(default='linear', help_text='linear, radial, conic', max_length=20)),
                ('direction', models.CharField(default='to right', help_text="e.g., 'to right', '45deg', 'circle'", max_length=50)),
                ('color_stops', models.JSONField(help_text='Array of color stops with positions')),
                ('css_value', models.TextField(blank=True, help_text='Generated CSS gradient value')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gradient Preset',
                'verbose_name_plural': 'Gradient Presets',
            },
        ),
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('theme_type', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('background_override', models.CharField(blank=True, max_length=7, null=True)),
                ('surface_override', models.CharField(blank=True, max_length=7, null=True)),
                ('text_primary_override', models.CharField(blank=True, max_length=7, null=True)),
                ('text_secondary_override', models.CharField(blank=True, max_length=7, null=True)),
                ('border_override', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='colors.colorpalette')),
            ],
            options={
                'verbose_name': 'Color Scheme',
                'verbose_name_plural': 'Color Schemes',
                'unique_together': {('palette', 'theme_type')},
            },
        ),
    ]
