# Generated by Django 5.0.8 on 2026-02-04 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='dark', max_length=10)),
                ('allow_user_customization', models.BooleanField(default=True)),
                ('brand_primary', models.CharField(default='#3b82f6', max_length=7)),
                ('brand_secondary', models.CharField(default='#8b5cf6', max_length=7)),
                ('brand_accent', models.CharField(default='#ec4899', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Theme Configuration',
                'verbose_name_plural': 'Global Theme Configuration',
            },
        ),
        migrations.CreateModel(
            name='ThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('theme_mode', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto (System)')], default='dark', max_length=10)),
                ('primary_color', models.CharField(default='#3b82f6', help_text='Hex color code', max_length=7)),
                ('accent_color', models.CharField(default='#8b5cf6', help_text='Hex color code', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Theme Preference',
                'verbose_name_plural': 'Theme Preferences',
            },
        ),
    ]
